### ISSUE TITLE
Move "Software Factory" (a.k.a. Big Bang Umbrella) example to a separate repo

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#270]
The "Software Factory" (a.k.a. Big Bang Umbrella) example is becoming the baseline for the "DI2-ME" work we are doing. We need to move it out of examples and into either a dedicated repo or a repo designed to support pre-built Zarf packages.

Acceptance Criteria:

- [x] Docs are updated
- [x] Works against Zarf v0.14.0 (will make new issue to update to v0.15.0 once it releases)
- [x] Folder re-added to Zarf repo with README.md that redirects the reader to the new repo.

**Comment by RothAndrew** [comment]
Created https://github.com/defenseunicorns/zarf-package-software-factory

**Comment by RothAndrew** [comment]
Acceptance Criteria:
1. Docs are updated
2. Works against Zarf v0.14.0 (will make new issue to update to v0.15.0 once it releases)
3. Folder re-added to Zarf repo with README.md that redirects the reader to the new repo.
