### ISSUE TITLE
WIP: Zarf UI POC

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#323]
### Objective

Design and build an POC for a Zarf UI that helps users without a coding background visualize the functionality, and quickly understand the value of the tool.

This is a prototype MVP  that will be used to text need/interest in a Zarf UI. Will be trashed if it does not add measurable value.

### Assumptions to Test

- Zarf UI will increase adoption, by making the Zarf process more understandable to non-technical stakeholders
- Zarf UI will increase adoption by lowering the barrier to entry to uses Zarf (ex. CLI)
- Zarf UI will increase user experience by making Zarf data and commands more discoverable and easier to execute.

### Use Cases (Prioritized Order)

1. How might the user discover what apps are running and get information regarding status. (Pods)
2. How might the user discover what packages are running and get information regarding status. (Helm Charts)
3. Deploying a new package - drag and drop

Example:  Argo (Web UI) and Flux (CLI) offer the same functionality but only one has a web UI

Plan
- [x] Discovery session with Jeff/Rob
- [x] Collaborative design session with Jeff (Wed)
- [x] Pick UI component library - MUI 
- [x] Build paper prototype of UI
- [x] Digitize paper prototype of UI (Maybe)
- [x] Build in code

---
Original Post

MVP: Create the minimum prototype needed to test riskiest assumptions

* Surfacing packages to install / package discovery
* Package upgradability
* Current state of the cluster. Visualizing what you have already deployed or installed
* Better visualization around the problem Zarf solves

---
3/3/2022
 - [] Add basic boilerplate routing to the navbar
 - [] Adding component page 
 - [] play around / research the Angular CLI and Angular DevTools Extension
 - [] learn how routing works in this Angular app (and document it whatever learned..)

**Comment by Madeline-UX** [comment]
### User Story 1

As a non-technical decision-maker,
I want to have the option to use a UI for Zarf
So I can understand how Zarf works under the hood without reading code. 
I am interested in high-level information like what apps are running and their status. 

### Acceptance Requirements

- [ ] Basic navigation
- [ ] Dashboard
- [ ] Active apps
- [ ] Application status
- [ ] Suggested actions if status changes?

### Key UX principles:
- Discoverability: User can easilty determine what actions are possible and the current state of the device
- Feedback: The system indicates when and how it is working when executing tasks.
- Conceptual Modeling: Application has all the information needed to create a good conceptual model of the system, leading to an understanding and a feeling of control
- Constraints: restrict the kind of interactions that can take place and therefore help reduce the amount of information we process

**Comment by Madeline-UX** [comment]
### User Story 2 - Helm Chart Dashboard

As a non-technical decision-maker,
I want to have the option to use a UI for Zarf
So I can understand how Zarf works under the hood without reading code. 
I am interested in high-level information like what packages are running and their current status

**Comment by jeff-mccoy** [comment]
When evaluating the need to "build vs buy",   We found it useful to evaluate various other K8s UIs that already exist.  

# Constraints:
- Must be open-source and compatible license
- Must be web-based UI, no desktop applications
- Must be easy for users 
- Must be easy to extend/customize
- Must have a healthy community, recent commits and multiple contributors (ideally majority US-based for govt customers)

# Decision:
Skooner presented the best balance of flexibility and simplicity to meet our needs of a Zarf UI, based on previously outlined design needs and the constraints above. The only real alternative in the "buy" category is the K8s Dashboard, but it didn't feel as close to what we are hoping to build for Zarf.

# Options
## [Skooner](https://skooner.io/overview/#why-skooner)
Excellent UI (simple, clean), very easy to customize/extend.  Modern stack, React/ExpressJS

## [K8s Dashboard](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/)
Good UI (material), but fairly complicated for novice users, a lot of data presented up-front.  

## [Octant](https://octant.dev/)
Interesting because it behaves similar to how we see Zarf with a go-based CLI launching a local webserver interface.  Really dated UI.  Also large/complex.

## [Weavescope](https://www.weave.works/docs/scope/latest/introducing/)
Novel interface, but confusing and somewhat flaky

## [Kubvious](https://github.com/kubevious/kubevious)
Really complicated UI

## [Konstellate](https://jeremykross.github.io/konstellate/)
Dead.

## [Kubernator](https://github.com/smpio/kubernator)
Dead.

## [Kubricks](https://github.com/kubricksllc/Kubricks)
Dead.

**Comment by Madeline-UX** [comment]
Screenshots of virtual design studio work that was used to inform the decision outlined above to customize Skooker's dashboard.
<img width="1481" alt="Screen Shot 2022-02-26 at 10 18 24 AM" src="https://user-images.githubusercontent.com/92826525/156080368-1cc9ecec-d559-4b4c-b3f8-7b0ca4f91c47.png">

<img width="1386" alt="Skooner-UI" src="https://user-images.githubusercontent.com/92826525/156080365-683a5b3d-846a-4df0-b52e-0d5a54116666.png">


<img width="1049" alt="Screen Shot 2022-02-28 at 6 10 22 PM" src="https://user-images.githubusercontent.com/92826525/156080362-be9a1a82-62fd-4955-bf4a-035175131311.png">

**Comment by Madeline-UX** [comment]
Zarf UI - Design 

Link: https://www.figma.com/file/FVxDm72mPiUTKmAD44ixmX/MUI-for-Figma-v5.4.0---Material-UI?node-id=8578%3A71616

##Dark Mode##
<img width="1178" alt="Screen Shot 2022-03-01 at 6 16 47 PM" src="https://user-images.githubusercontent.com/92826525/156618384-57ef17f8-2a99-46b7-84fb-f9d9a5fe5c2a.png">

##Light Mode##
<img width="1180" alt="Screen Shot 2022-03-01 at 6 17 22 PM" src="https://user-images.githubusercontent.com/92826525/156618389-9e753474-48e5-4e4b-ae82-393557787681.png">

**Comment by YrrepNoj** [comment]
@Madeline-UX Is this issue completed now that #727 has been merged in?

**Comment by Madeline-UX** [comment]
The proof of concept was completed back in June and findings have been integrated and iteraged on into the new UI. So in summary yes.
