### ISSUE TITLE
Epic: Add support for RKE 2

### ISSUE THREAD

**Issue by JasonvanBrackel** [defenseunicorns/zarf#853]
As a Platform Engineer, I want to use Zarf to Deploy and Manage and RKE2 Cluster

We've been asked by numerous users to support RKE 2.  This is technologically feasible as RKE 2's deployment and runtime model are derived from k3s which we already support.

- [ ] #854 Create initial POC of RKE 2 Zarf Init Package that matches K3s
---------
Issues TBD
- [ ] Create a model and pattern for production deployment  of a RKE 2
  - [ ] Capability must be able to add and remove nodes as needed either via autoscaling capabilities or manual changes
  - [ ] Create documentation for continued management of an RKE 2 cluster zarf
    - [ ] Docs site
    - [ ] Videos

This represents a bare minimum for support, but will be fleshed out further once the POC is out.

**Comment by Racer159** [comment]
Closing this to deprecate the use of Epics in favor of milestones
