### ISSUE TITLE
Epic: Public GitHub Actions to Enable Teams to Easily Ingest Zarf for CI/CD testing in their pipelines.

### ISSUE THREAD

**Issue by JasonvanBrackel** [defenseunicorns/zarf#855]
In order to certify that my application can support airgap use cases, 
As a development team 
I want a set of GitHub Actions to enable me to easily do AirGap deployment testing in my CI/CD pipelines.

- [x] Determination of a proto CI/CD workflow required to meet this user story - To Be Documented here.
- [ ] Break this workflow into GitHub Actions, for each action
  - [x] Develop the GitHub Action in its own repository as is the pattern recommended by [Microsoft's GitHub Training for Creating and Publishing GitHub Actions](https://learn.microsoft.com/en-us/training/modules/create-custom-github-actions/)
  - [x] A Lifecycle model supported by GitHub Actions
  - [x] A Lifecycle workflow that changes using automation when Zarf changes
  - [x] Documentation for the GitHub Action using https://github.com/actions as guide for how we ought to document them.
  - [x] Integrate the GitHub Action into our own pipelines
  - [ ] Videos content using the GitHub Action in our own pipelines

**Comment by jeff-mccoy** [comment]
Mostly done with https://github.com/defenseunicorns/setup-zarf

**Comment by Racer159** [comment]
With the upgrade test we now have this action in our pipeline was there more we wanted from this?

**Comment by Noxsios** [comment]
Agree @Racer159 , I think we can safely close this @jeff-mccoy

**Comment by Racer159** [comment]
Closing as completed
